--1)
CREATE OR REPLACE PROCEDURE EXERCICIO_01 (pIDPedido in Number) AS
BEGIN
UPDATE PEDIDO ped
SET ped.VALORPEDIDO = ( SELECT  SUM(QUANTIDADE * PRECOUNITARIO)
                        FROM    PEDIDOITEM
                        WHERE   IDPEDIDO = ped.IDPEDIDO)
WHERE ped.IDPEDIDO = pIDPedido;
END;

--2)
CREATE OR REPLACE FUNCTION EXERCICIO_02 (pIDCliente in Number) RETURN PEDIDO.DATAPEDIDO%TYPE AS
 vData PEDIDO.DATAPEDIDO%TYPE;
BEGIN 
 SELECT MAX(DATAPEDIDO)
 INTO vData
 FROM PEDIDO
 WHERE IDCLIENTE = pIDCliente;
 
 RETURN vData;
END;

--3)
CREATE OR REPLACE FUNCTION EXERCICIO_03 (pIDProduto in Number, pPeriodo in Date) RETURN PEDIDOITEM.QUANTIDADE%TYPE AS
 vQuantidadeTotal PEDIDOITEM.QUANTIDADE%TYPE;
BEGIN

SELECT SUM(pedidoitem.QUANTIDADE)
INTO vQuantidadeTotal
FROM PEDIDOITEM pedidoitem
INNER JOIN PEDIDO pedido ON pedidoitem.IDPEDIDO = pedido.IDPEDIDO
WHERE pedido.Datapedido BETWEEN TRUNC(pPeriodo,'MM') AND LAST_DAY(pPeriodo)
      AND pedidoitem.IDPRODUTO = pIDProduto;

RETURN  vQuantidadeTotal;
END;
