INSERT INTO PESSOA (ID_PESSOA, NM_PESSOA) VALUES ((SELECT NVL(MAX(ID_PESSOA), 0) + 1 FROM PESSOA), 'BBBBBBBBBBBBBBBBBBBBBBBB');
INSERT INTO PESSOA (ID_PESSOA, NM_PESSOA) VALUES ((SELECT NVL(MAX(ID_PESSOA), 0) + 1 FROM PESSOA), 'BBBBBBBBBBBBBBBBBBBBBBBB');
INSERT INTO PESSOA (ID_PESSOA, NM_PESSOA) VALUES ((SELECT NVL(MAX(ID_PESSOA), 0) + 1 FROM PESSOA), 'BBBBBBBBBBBBBBBBBBBBBBBB');
INSERT INTO PESSOA (ID_PESSOA, NM_PESSOA) VALUES ((SELECT NVL(MAX(ID_PESSOA), 0) + 1 FROM PESSOA), 'BBBBBBBBBBBBBBBBBBBBBBBB');
INSERT INTO PESSOA (ID_PESSOA, NM_PESSOA) VALUES ((SELECT NVL(MAX(ID_PESSOA), 0) + 1 FROM PESSOA), 'BBBBBBBBBBBBBBBBBBBBBBBB');
