INSERT INTO PESSOA (ID_PESSOA, NM_PESSOA) VALUES ((SELECT NVL(MAX(ID_PESSOA), 0) + 1 FROM PESSOA), 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA');
INSERT INTO PESSOA (ID_PESSOA, NM_PESSOA) VALUES ((SELECT NVL(MAX(ID_PESSOA), 0) + 1 FROM PESSOA), 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA');
INSERT INTO PESSOA (ID_PESSOA, NM_PESSOA) VALUES ((SELECT NVL(MAX(ID_PESSOA), 0) + 1 FROM PESSOA), 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA');
INSERT INTO PESSOA (ID_PESSOA, NM_PESSOA) VALUES ((SELECT NVL(MAX(ID_PESSOA), 0) + 1 FROM PESSOA), 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA');
INSERT INTO PESSOA (ID_PESSOA, NM_PESSOA) VALUES ((SELECT NVL(MAX(ID_PESSOA), 0) + 1 FROM PESSOA), 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA');
